### ISSUE TITLE
`antigen init` freeze my shell

### ISSUE THREAD

**Issue by dolphin-wood** [VincentBel/dotfiles#2]
The command `antigen init .antigenrc` here [.zshrc#L22](https://github.com/VincentBel/dotfiles/blob/master/.zshrc#L22) makes my shell frozen 😢 

Thought that we should change it into `source ~/.antigenrc`.

**Comment by vincentbel** [comment]
I have no idea why `source ~/.antigenrc` works but `antigen init .antigenrc` failed. 

As you can see the [implementation detail of `antigen init`(v1.2.3)](https://github.com/zsh-users/antigen/blob/v1.2.3/src/ext/zcache.zsh#L124-L163), it just checks the cache and `soruce` it if cache not exist.

I think you can check your antigen version by `antigen version`, and use a fresh version to try again😅. (may be you can add some log to the `antigen init` implementation detail to see what hung up)

**Comment by dolphin-wood** [comment]
@VincentBel I was using the latest version of antigen(v1.2.3), but still failed...

**Comment by vincentbel** [comment]
@idiotWu After updated antigen from 1.1.0 to 1.2.3, I had the same problem. Wait for the reply from https://github.com/zsh-users/antigen/issues/321.

**Comment by vincentbel** [comment]
@idiotWu Should works after antigen `v1.2.4` released. Will close this after released.

**Comment by dolphin-wood** [comment]
@VincentBel got it.
